version: "3"

services: 
  python:
    container_name: python_container
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - ./project:/work
    command: /bin/sh -c "while :; do sleep 10; done"